baseurl = "https://udeshyadhungana.github.io
title = "Udeshya"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
  author = "Udeshya Dhungana"
  info = "Programming. Math. Health."
  description = "Iris' Blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  footercontent = "Post Proelium, Praemium"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/images/favicon.ico"
  favicon_16 = "/images/favicon.ico"

  since = 2020

  # enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Udeshyadhungana/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/udeshyadhungana/"

# Menu links
[[menu.main]]
  name = "Articles"
  weight = 1
  url  = "articles/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
