#+TITLE: Linear Regression
#+DATE: 2021-05-04
#+TAGS[]: maths, linear regression, machine learning, computer science
#+CATEGORIES[]: Mathematics, Computer Science
#+MATH: true

Hello, today I want to write about Linear Regression. It is basically
the "Hello, World" program of Machine Learning.  It is used to model
the relationship between one or more inputs and a single output. It
has various applications ranging from engineering to business. Since
it is a process of learning from data, more the data, more the
accuracy of model.  Regarding the algorithm, we have a set of input
($X$) and their corresponding outputs ($Y$). From this,we try to come
up with an equation that best fits the data. Then, we can use that
equation to predict the output for new inputs.

There are mainly two ways to solve a linear regression problem. They
are

- Least Mean Square Algorithm
- Normal Equations

Both of these will be explained in the article, but first, let us
state the problem a bit more clearly to avoid any confusion.  Our
dataset consists a $n+1$ items, where each item has a set of $d$
features, $x_i$'s, and a corresponding output, $y$. We can summarize
this information in following matrices.

$$ X_{n \times d} = \begin{bmatrix} (x^{(0)})^{T} \\ (x^{(1)})^{T}
\\ \vdots \\ (x^{(n)})^{T} \\ \end{bmatrix} $$

$$ x^{(i)}_{d\space \times 1} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots
\\ x_{d} \\ \end{bmatrix} $$

$$ Y_{n\space \times 1} = \begin{bmatrix} y^{(0)} \\ y^{(1)} \\ \vdots
\\ y^{(n)} \\ \end{bmatrix} $$

Remember that the entry in the second matrix starts from $1$, not
$0$. I have done it deliberately to make calculations easier.  Our
goal is to create a hypothesis function, $h$, that maps a new input
item $x$ to its corresponding output $y$. Since this is a linear
regression problem, it is obvious to think that the hypothesis
function produces the outputs as the /linear combination/ of input,
i.e. the hypothesis function scales each feature by some amount and
sums them up including a constant term. We will denote the scaling
factors and constants by $\theta$. As there are $d$ features, scaling
every feature would require $d$ parameters. We also need a constant
term. So, in total, we need $d+1$ thetas, subscripted from $0$ to $d$,
where $\theta_0$ is the constant term. So, our hypothesis function
looks like this:

$$ h(x) = \theta_0 + \sum_{i=1}^{d} \theta_{i} x_{i} $$

Now, our goal is to find these $\theta$'s.

* Least Mean Square (LMS) Algorithm

It is an algorithm to find these parameters. In this algorithm, we
define an error function $J(\theta)$, that is an indicator of the
degree of error present in our model.  The lower the value of
$J(\theta)$, the better values of parameters we have. So, we will have
obtained the best fit if the error is as low as possible. The best
choice of error function is the following function:


$$ J(\theta) = \frac{1}{2} \sum_{i=1}^{n} (h(x^{(i)}) - y^{(i)})^{2}
$$

There are other error functions as well, but we will use this
function. It effectively captures the error present in our model
because each term in the series is the squared difference between the
true value of $y$ and our prediction $h(x)$. Hence, larger the
difference, larger the error.  Notice that if we don't include the
square, the positive and negative difference may cancel out, the error
may be reduced, but difference still exists.  So, it is important to
remove both overprediction and underprediction.

Since this has been reduced to a minimization problem, we can use
calculus to make our work easier. Remember that our goal is to adjust
the parameters, $\theta$, to have optimum value. So, we take the
derivative of the cost function, $J(\theta)$ with respect to each
$\theta$ and then update the value of each $\theta$ to make
$J(\theta)$ smaller. The cost function we have defined above is the
cost considering all the training examples. For a single training
example, the cost is given as:

$$ J_i(\theta) = \frac{1}{2} (h(x^{(i)}) - y^{(i)})^{2} $$

The derivative of this function with respect to a particular
$\theta_{j}$ is given as

$$ \frac{\partial }{\partial \theta_{j}} J_i(\theta) =
\frac{\partial}{\partial \theta_{j}} \frac{1}{2} (h(x^{(i)}) -
y^{(i)})^2 $$

We must update the values of $\theta{j}$:

$$ \theta_{j} := \theta_{j} - \alpha \frac{\partial}{\partial
\theta_{j}} J(\theta) $$ $$ \theta_{j} := \theta_{j} + \alpha
(y^{(i)} - h(x^{(i)})) \space x_{j}^{(i)} $$

Here, $\alpha$ is the learning rate. Suitable value of $\alpha$ should
be chosen. If it is too small, convergence may take more
time. Whereas, bigger value of $\alpha$ may not result in
covergence. Now, this update must be subjected to all the thetas, and
must be done considering all the training examples. There are two ways
of updating the values.

If we update the value of a single theta considering the all the
training examples at once. This is called batch gradient descent. The
algorithm for this is

$Repeat\space until\space convergence\space$ { $$ \theta_{j} :=
\theta_{j} + \alpha \sum_{i=1}^n \space(y^{(i)} - h(x^{(i)})) \space
x_{j}^{(i)}, \quad (for\space every\space j) $$ }

On the other hand, if we updae the values of $\theta$s by only looking
at a single training example, it is called stochastic gradient
descent. It is implemented as:

$Loop$ { \\ $\quad for\space i = 1\space to\space n$ { $$ \theta_{j}
:= \theta_{j} + \alpha (y^{(i)} - h(x^{(i)})) \space x_{j}^{(i)},
\quad (for\space every\space j) $$ $\quad$}\\ }

So, among batch GD and stochastic GD, which one should we use then?
Upon looking the algorithm of batch GD, we find that there's a
significant calculation before updating the values of theta as we have
to calculate the summation term. So, this method is slower than
stochastic GD, which updates the value of theta looking at just one
training example at a time. This can speed up convergence. For faster
calculation, we must [[https://en.wikipedia.org/wiki/Vectorization][vectorize]] the entire operation.

* Normal Equations

We can carry out this operation of Least Square Minimization (LSM)
even without using calculus. As above, our dataset consists of $X$ and
$Y$. We have to find the $\theta$'s for which following equation
satisfies:

$$
\begin{bmatrix}1 & (x^{(0)})^{T}\\1 & (x^{(1)})^{T}\\\vdots\\1 & (x^{(n)})^{T}\\\end{bmatrix}
\begin{bmatrix}\theta_0\\\theta_1\\\vdots\\\theta_d\end{bmatrix} =
\begin{bmatrix}y^{(0)}\\y^{(1)}\\\vdots\\y^{(n)}\end{bmatrix}
$$ $$ A \quad \quad \quad \quad \quad \theta\quad =\quad Y $$

The matrix $A$ is a matrix formed by augmenting a column with all
elements 1 in front of matrix X. Alas! This system of equation will
hardly have an exact solution, because the probability of all our data
sets lying exactly on our fitting curve is near to zero. So, what
should we do then? We must project the vectory $Y$ onto the column
space of $A$. Now that a lot of words. Here a short section on
familiarizing you with some frequently used terms. If you are already
familiar with linear algebra, you can skip next section. Morever,
these are not accurate mathematical definitions but will be sufficient for our
purpose.

*** Some Terms

[[https://en.wikipedia.org/wiki/Linear_combination][*Linear Combination*]] of a set of vectors is an expression constructed
by multiplying each vector in the set by some constant and adding the
results.  For example, a linear combination of $\vec{i}$, unit vector
in x direction, and $\vec{j}$, unit vector in y direction would be
$a\vec{i} + b\vec{j}$.

A set of vectors are [[https://en.wikipedia.org/wiki/Linear_independence][*Linearly Independent*]] if there is a linear
combination of the vectors equals zero vector, then each of the
multiplying factors must be zero.  For example, vectors $\vec{i}$ and
$\vec{j}$ are independent, because no linear combination $a\vec{i} +
b\vec{j}$ would produce zero vector, except for $a = 0$ and $b = 0$.

[[https://en.wikipedia.org/wiki/Vector_space][*Vector Space*]] is a set of vectors such that they are closed under
linear combination. That is, the linear combination of vectors inside
the vector space will produce a vector which is also inside the
space. $\mathcal{R}^{N}$ is a vector space because any vector
resulting from linear combination of the vectors inside
$\mathcal{R}^{N}$ will stay inside $\mathcal{R}^{N}$.

A [[https://en.wikipedia.org/wiki/Linear_subspace][*subspace*]] is a subset of some larger vector space. A plane passing
through origin can be considered a subspace inside
$\mathcal{R}^{3}$. It is because it is a subset of $\mathcal{R}^{3}$
and linear combination of any number of vectors lying inside the plane
will result in a vector which also lies inside it.

A [[https://en.wikipedia.org/wiki/Linear_span][Linear Span]] of a set of vectors is the subspace that is formed by
linear combination of all the vectors in the set. For example, For
$S = {\vec{i}, \vec{j}}$, the span is $\mathcal{R}^{2}$ because from
the linear combination of $\vec{i}$ and $\vec{j}$, every vector in
$\mathcal{R}^{2}$ can be constructed. In other words, these two vectors
/reach/ entire $\mathcal{R}^{2}$.

[[https://en.wikipedia.org/wiki/Row_and_column_spaces][Column Space]] of a matrix is the subspace formed by the column vectors
of the matrix. For a matrix $\begin{bmatrix}1 & 2\\3 & 4\end{bmatrix}$,
its columnspace is $\mathcal{R}^{2}$. Since the columns of this matrix
are linearly independent, their linear combination can /reach/ the entire
$\mathcal{R}^{2}$. Whereas, for a matrix $\begin{bmatrix}1 & 0 & 1\\0 & 1 & 1\\0 & 0 & 0\end{bmatrix}$,
the columnspace is the x-y plane inside $\mathcal{R}^{3}$. It is not $\mathcal{R}^{3}$
because the linear combination only yields the vector of the
form $\begin{bmatrix}a\\b\\0\end{bmatrix}$. The third column can be constructed
as $1 \cdot (Column 1) + 1 \cdot (Column 2)$. So it does not help in the construction
of columnspace.

These terminologies will suffice. Now let's move forward to understanding projection
and projection matrices.

*** Projection

Let's say we want to project a vector $\vec{b}$ onto a vector $\vec{a}$. How do we do this?
First, let's denote some terms to make it easier. We'll refer to the projection of $\vec{b}$ onto
$\vec{a}$ as $\vec{p}$. We also draw a vector from $\vec{p}$ to the tip of  vector $\vec{b}$.
It will be called /error/ vector. It is given as $\vec{e} = \vec{b} - \vec{p}$. Let's compute
$\vec{p}$. We know that $\vec{p}$ is a multiple of $\vec{a}$ as it lies in the same line as $\vec{a}$.
So, we can write $\vec{p} = \hat{x} \cdot \vec{a}$. Since $\vec{a}$ and $\vec{e}$ are perpendicular to each
other, we can write

$$
\vec{a} \cdot \vec{e} = 0
$$

$$
\vec{a} \cdot (\vec{b} - \vec{p}) = 0
$$

$$
\vec{a} \cdot (\vec{b} - \hat{x} \cdot \vec{a}) = 0
$$

On simple calculation, it yields

$$
\hat{x} = \frac{\vec{a} \cdot \vec{b}}{\vec{a} \cdot \vec{a}} = \frac{a^{T} \cdot b}{a^{T} \cdot a}
$$

We can substitute dot product for vectors by multiplicaton of transpose of one with the other. It's a really
trivial calculation. Try it out for yourself if you're still confused.
